/* ************************************************************************************************/ // clang-format off
// flipflip's cfggui
//
// Copyright (c) 2021 Philippe Kehl (flipflip at oinkzwurgl dot org),
// https://oinkzwurgl.org/hacking/ubloxcfg
//
// This program is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
// even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program.
// If not, see <https://www.gnu.org/licenses/>.

#include "mapparams.hpp"

/* ****************************************************************************************************************** */

/*static*/ const std::vector<MapParams> MapParams::BUILTIN_MAPS =
{
    {
        .enabled         = true,
        .name            = "osm",
        .title           = "OpenStreetMap",
        .attribution     = "OpenStreetMap contributor",
        .attrLink        = "https://www.openstreetmap.org/copyright",
        .license         = "ODbL",
        .licenseLink     = "https://opendatacommons.org/licenses/odbl/",
        .policy          = "Tile usage policy",
        .policyLink      = "https://operations.osmfoundation.org/policies/tiles/",
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmch",
        .title           = "OpenStreetMap CH",
        .attribution     = "OpenStreetMap contributors",
        .attrLink        = "https://osm.ch",
        .license         = "ODbL",
        .licenseLink     = "https://opendatacommons.org/licenses/odbl/",
        .policy          = "Terms of service",
        .policyLink      = "https://sosm.ch/about/terms-of-service/",
        .zoomMin         = 0,
        .zoomMax         = 21,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://tile.osm.ch/switzerland/{z}/{x}/{y}.png",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmde",
        .title           = "OpenStreetMap DE",
        .attribution     = "OpenStreetMap contributors",
        .attrLink        = "https://www.openstreetmap.de/",
        .license         = "ODbL",
        .licenseLink     = "https://opendatacommons.org/licenses/odbl/",
        .policy          = "FAQ",
        .policyLink      = "https://www.openstreetmap.de/faq.html#lizenz",
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.de/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "otm",
        .title           = "OpenTopoMap",
        .attribution     = "OpenStreetMap contributors, SRTM, OpenTopoMap",
        .attrLink        = "https://opentopomap.org/about",
        .license         = "ODbL",
        .licenseLink     = "https://opendatacommons.org/licenses/odbl/",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 17,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmfr",
        .title           = "OpenStreetMap FR",
        .attribution     = "OpenStreetMap contributors, OpenStreetMap France",
        .attrLink        = "https://www.openstreetmap.fr/fonds-de-carte/",
        .license         = "ODbL",
        .licenseLink     = "https://opendatacommons.org/licenses/odbl/",
        .policy          = "Données",
        .policyLink      = "https://www.openstreetmap.fr/donnees/",
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmfr_hum",
        .title           = "OpenStreetMap FR Humanitarian",
        .attribution     = "OpenStreetMap contributors, OpenStreetMap France",
        .attrLink        = "https://www.openstreetmap.fr/fonds-de-carte/",
        .license         = "ODbL",
        .licenseLink     = "https://opendatacommons.org/licenses/odbl/",
        .policy          = "Données",
        .policyLink      = "https://www.openstreetmap.fr/donnees/",
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        // http://maps.stamen.com/toner/
        .enabled         = true,
        .name            = "stamen_toner",
        .title           = "Stamen toner",
        .attribution     = "Map tiles by Stamen Design (CC BY 3.0). Data by OpenStreetMap (ODbL)",
        .attrLink        = "http://maps.stamen.com/",
        .license         = "CC BY-SA",
        .licenseLink     = "https://creativecommons.org/licenses/by-sa/3.0/",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 12,
        .zoomMax         = 12,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c", "d" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        // http://maps.stamen.com/terrain/
        .enabled         = true,
        .name            = "stamen_terrain",
        .title           = "Stamen terrain",
        .attribution     = "Map tiles by Stamen Design (CC BY 3.0). Data by OpenStreetMap (ODbL)",
        .attrLink        = "http://maps.stamen.com/",
        .license         = "CC BY-SA",
        .licenseLink     = "https://creativecommons.org/licenses/by-sa/3.0/",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 12,
        .zoomMax         = 12,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://{s}.tile.stamen.com/terrain/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c", "d" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        // http://maps.stamen.com/watercolor/
        .enabled         = true,
        .name            = "stamen_watercolor",
        .title           = "Stamen watercolor",
        .attribution     = "Map tiles by Stamen Design (CC BY 3.0). Data by OpenStreetMap (ODbL)",
        .attrLink        = "http://maps.stamen.com/",
        .license         = "CC BY-SA",
        .licenseLink     = "https://creativecommons.org/licenses/by-sa/3.0/",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 12,
        .zoomMax         = 12,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c", "d" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        // https://openstreetmap.maps.arcgis.com/
        .enabled         = true,
        .name            = "esri_world",
        .title           = "ESRI world imagery",
        .attribution     = "i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
        .attrLink        = "https://openstreetmap.maps.arcgis.com/",
        .license         = "", // TODO
        .licenseLink     = "",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 21,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{y}/{x}.png",
        .minLat          = MIN_LAT,
        .maxLat          = MAX_LAT,
        .minLon          = MIN_LON,
        .maxLon          = MAX_LON,
        .threads         = 2,
    },
    {
        // https://www.swisstopo.admin.ch/en/swisstopo/free-geodata.html
        // https://www.geo.admin.ch/en/about-swiss-geoportal/responsabilities-and-contacts.html
        // https://www.geo.admin.ch/vanity/geo-internet/terms-of-use
        // https://map.geo.admin.ch
        // https://api3.geo.admin.ch/services/sdiservices.html
        // https://wmts.geo.admin.ch/EPSG/3857/1.0.0/WMTSCapabilities.xml
        .enabled         = true,
        .name            = "chlk_f",
        .title           = "Swisstopo Landeskarten (farbig)",
        .attribution     = "© swisstopo",
        .attrLink        = "https://www.swisstopo.admin.ch",
        .license         = "Terms of use",
        .licenseLink     = "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html",
        .policy          = "", // covered in the above
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_g",
        .title           = "Swisstopo Landeskarten (grau)",
        .attribution     = "© swisstopo",
        .attrLink        = "https://www.swisstopo.admin.ch",
        .license         = "Terms of use",
        .licenseLink     = "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-grau/default/current/3857/{z}/{x}/{y}.jpeg",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_si",
        .title           = "Swisstopo Swissimage",
        .attribution     = "© swisstopo",
        .attrLink        = "https://www.swisstopo.admin.ch",
        .license         = "Terms of use",
        .licenseLink     = "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/{z}/{x}/{y}.jpeg",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_df",
        .title           = "Swisstopo Dufourkarte Erstausgaben (1844-1864, 1939)",
        .attribution     = "© swisstopo",
        .attrLink        = "https://www.swisstopo.admin.ch",
        .license         = "Terms of use",
        .licenseLink     = "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 18,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.hiks-dufour/default/18650101/3857/{z}/{x}/{y}.png",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_sg",
        .title           = "Swisstopo Siegfriedkarte Erstausgabe (1870-1926)",
        .attribution     = "© swisstopo",
        .attrLink        = "https://www.swisstopo.admin.ch",
        .license         = "Terms of use",
        .licenseLink     = "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 17,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.hiks-siegfried/default/19260101/3857/{z}/{x}/{y}.png",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        .enabled         = false,
        .name            = "test_0_25",
        .title           = "test map 0..25",
        .attribution     = "test map",
        .attrLink        = "https://oinkzwurgl.org",
        .license         = "Terms of use",
        .licenseLink     = "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 25,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://tiletest.png",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        .enabled         = false,
        .name            = "test_0_20",
        .title           = "test map 0..20",
        .attribution     = "test map",
        .attrLink        = "https://oinkzwurgl.org",
        .license         = "",
        .licenseLink     = "",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://tiletest.png",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        .enabled         = false,
        .name            = "test_10_20",
        .title           = "test map 10..20",
        .attribution     = "test map",
        .attrLink        = "https://oinkzwurgl.org",
        .license         = "",
        .licenseLink     = "",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 10,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://tiletest.png",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
    {
        .enabled         = false,
        .name            = "test_0_25_200x100",
        .title           = "test map 0..25 200x100",
        .attribution     = "test map",
        .attrLink        = "https://oinkzwurgl.org",
        .license         = "",
        .licenseLink     = "",
        .policy          = "",
        .policyLink      = "",
        .zoomMin         = 0,
        .zoomMax         = 25,
        .tileSizeX       = 200,
        .tileSizeY       = 100,
        .downloadUrl     = "builtin://tiletest.png",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = 45.398181 * (M_PI / 180.0),
        .maxLat          = 48.230651 * (M_PI / 180.0),
        .minLon          =  5.140242 * (M_PI / 180.0),
        .maxLon          = 11.477570 * (M_PI / 180.0),
        .threads         = 2,
    },
};

/* ****************************************************************************************************************** */
