/* ************************************************************************************************/ // clang-format off
// flipflip's cfggui
//
// Copyright (c) 2021 Philippe Kehl (flipflip at oinkzwurgl dot org),
// https://oinkzwurgl.org/hacking/ubloxcfg
//
// This program is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
// even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program.
// If not, see <https://www.gnu.org/licenses/>.

#include "mapparams.hpp"

/* ****************************************************************************************************************** */

#define SWISSTOPO_MIN_LAT   ( 45.398181 * (M_PI / 180.0) )
#define SWISSTOPO_MAX_LAT   ( 48.230651 * (M_PI / 180.0) )
#define SWISSTOPO_MIN_LON   (  5.140242 * (M_PI / 180.0) )
#define SWISSTOPO_MAX_LON   ( 11.477570 * (M_PI / 180.0) )

/*static*/ const std::vector<MapParams> MapParams::BUILTIN_MAPS =
{
    {
        .enabled         = true,
        .name            = "osm",
        .title           = "OpenStreetMap",
        .mapLinks        = { { "OpenStreetMap contributors", "https://www.openstreetmap.org/copyright" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" },
                             { "Tile usage policy", "https://operations.osmfoundation.org/policies/tiles/" }, },
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmch",
        .title           = "OpenStreetMap CH",
        .mapLinks        = { { "OpenStreetMap contributors", "https://osm.ch" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" },
                             { "Terms of service", "https://sosm.ch/about/terms-of-service/" }, },
        .zoomMin         = 0,
        .zoomMax         = 21,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://tile.osm.ch/switzerland/{z}/{x}/{y}.png",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmde",
        .title           = "OpenStreetMap DE",
        .mapLinks        = { { "OpenStreetMap contributors", "https://www.openstreetmap.de/" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" },
                             { "FAQ", "https://www.openstreetmap.de/faq.html#lizenz" }, },
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.de/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "otm",
        .title           = "OpenTopoMap",
        .mapLinks        = { { "OpenStreetMap contributors, SRTM, OpenTopoMap", "https://opentopomap.org/about" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" }, },
        .zoomMin         = 0,
        .zoomMax         = 17,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmfr",
        .title           = "OpenStreetMap FR",
        .mapLinks        = { { "OpenStreetMap contributors, OpenStreetMap France", "https://www.openstreetmap.fr/fonds-de-carte/" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" },
                             { "Données", "https://www.openstreetmap.fr/donnees/" }, },
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        .enabled         = true,
        .name            = "osmfr_hum",
        .title           = "OpenStreetMap FR Humanitarian",
        .mapLinks        = { { "OpenStreetMap contributors, OpenStreetMap France", "https://www.openstreetmap.fr/fonds-de-carte/" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" },
                             { "Données", "https://www.openstreetmap.fr/donnees/" }, },
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        // http://maps.stamen.com/toner/
        .enabled         = true,
        .name            = "stamen_toner",
        .title           = "Stamen toner",
        .mapLinks        = { { "Map tiles by Stamen Design. Data by OpenStreetMap.", "http://maps.stamen.com/" },
                             { "CC BY-SA", "https://creativecommons.org/licenses/by-sa/3.0/" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" }, },
        .zoomMin         = 12,
        .zoomMax         = 12,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c", "d" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        // http://maps.stamen.com/terrain/
        .enabled         = true,
        .name            = "stamen_terrain",
        .title           = "Stamen terrain",
        .mapLinks        = { { "Map tiles by Stamen Design. Data by OpenStreetMap.", "http://maps.stamen.com/" },
                             { "CC BY-SA", "https://creativecommons.org/licenses/by-sa/3.0/" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" }, },
        .zoomMin         = 12,
        .zoomMax         = 12,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://{s}.tile.stamen.com/terrain/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c", "d" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        // http://maps.stamen.com/watercolor/
        .enabled         = true,
        .name            = "stamen_watercolor",
        .title           = "Stamen watercolor",
        .mapLinks        = { { "Map tiles by Stamen Design. Data by OpenStreetMap.", "http://maps.stamen.com/" },
                             { "CC BY-SA", "https://creativecommons.org/licenses/by-sa/3.0/" },
                             { "ODbL", "https://opendatacommons.org/licenses/odbl/" }, },
        .zoomMin         = 12,
        .zoomMax         = 12,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.png",
        .subDomains      = { "a", "b", "c", "d" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        // https://openstreetmap.maps.arcgis.com/
        .enabled         = true,
        .name            = "esri_world",
        .title           = "ESRI world imagery",
        .mapLinks        = { { "i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
                               "https://openstreetmap.maps.arcgis.com/" } }, // TODO: license
        .zoomMin         = 0,
        .zoomMax         = 21,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{y}/{x}.png",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 2,
    },
    {
        // https://www.swisstopo.admin.ch/en/swisstopo/free-geodata.html
        // https://www.geo.admin.ch/en/about-swiss-geoportal/responsabilities-and-contacts.html
        // https://www.geo.admin.ch/vanity/geo-internet/terms-of-use
        // https://map.geo.admin.ch
        // https://api3.geo.admin.ch/services/sdiservices.html
        // https://wmts.geo.admin.ch/EPSG/3857/1.0.0/WMTSCapabilities.xml
        .enabled         = true,
        .name            = "chlk_f",
        .title           = "Swisstopo Landeskarten (farbig)",
        .mapLinks        = { { "© swisstopo", "https://www.swisstopo.admin.ch" },
                             { "Terms of use", "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html" },
                             { "Meta data", "https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/f9c31be1-887c-4203-8b11-57b40ecc039b" }, },
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = SWISSTOPO_MIN_LAT,
        .maxLat          = SWISSTOPO_MAX_LAT,
        .minLon          = SWISSTOPO_MIN_LON,
        .maxLon          = SWISSTOPO_MAX_LON,
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_g",
        .title           = "Swisstopo Landeskarten (grau)",
        .mapLinks        = { { "© swisstopo", "https://www.swisstopo.admin.ch" },
                             { "Terms of use", "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html" },
                             { "Meta data", "https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/74aef814-0c97-4261-a2c1-df4a948aca8e" }, },
        .zoomMin         = 0,
        .zoomMax         = 19,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-grau/default/current/3857/{z}/{x}/{y}.jpeg",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = SWISSTOPO_MIN_LAT,
        .maxLat          = SWISSTOPO_MAX_LAT,
        .minLon          = SWISSTOPO_MIN_LON,
        .maxLon          = SWISSTOPO_MAX_LON,
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_si",
        .title           = "Swisstopo Swissimage",
        .mapLinks        = { { "© swisstopo", "https://www.swisstopo.admin.ch" },
                             { "Terms of use", "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html" },
                             { "Meta data", "https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/b52cd8fc-bd4a-4984-b951-0fe9cae2493f" }, },
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/{z}/{x}/{y}.jpeg",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = SWISSTOPO_MIN_LAT,
        .maxLat          = SWISSTOPO_MAX_LAT,
        .minLon          = SWISSTOPO_MIN_LON,
        .maxLon          = SWISSTOPO_MAX_LON,
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_df",
        .title           = "Swisstopo Dufourkarte Erstausgaben (1844-1864, 1939)",
        .mapLinks        = { { "© swisstopo", "https://www.swisstopo.admin.ch" },
                             { "Terms of use", "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html" },
                             { "Meta data", "https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/d12f970f-6a83-4c33-8cfe-7504b6a5dca9" }, },
        .zoomMin         = 0,
        .zoomMax         = 18,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.hiks-dufour/default/current/3857/{z}/{x}/{y}.png",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = SWISSTOPO_MIN_LAT,
        .maxLat          = SWISSTOPO_MAX_LAT,
        .minLon          = SWISSTOPO_MIN_LON,
        .maxLon          = SWISSTOPO_MAX_LON,
        .threads         = 2,
    },
    {
        // see "chlk_f" above
        .enabled         = true,
        .name            = "chlk_sg",
        .title           = "Swisstopo Siegfriedkarte Erstausgabe (1870-1926)",
        .mapLinks        = { { "© swisstopo", "https://www.swisstopo.admin.ch" },
                             { "Terms of use", "https://www.geo.admin.ch/en/geo-services/geo-services/terms-of-use.html" },
                             { "Meta data", "https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/d3b21424-70a4-4984-a693-aa7f11813c53" }, },
        .zoomMin         = 0,
        .zoomMax         = 17,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "https://{s}.geo.admin.ch/1.0.0/ch.swisstopo.hiks-siegfried/default/current/3857/{z}/{x}/{y}.png",
        .subDomains      = { "wmts" },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "{z}/{x}/{y}.png",
        .minLat          = SWISSTOPO_MIN_LAT,
        .maxLat          = SWISSTOPO_MAX_LAT,
        .minLon          = SWISSTOPO_MIN_LON,
        .maxLon          = SWISSTOPO_MAX_LON,
        .threads         = 2,
    },
    {
        .enabled         = false,
        .name            = "test_0_25",
        .title           = "test map 0..25",
        .mapLinks        = { { "test map", "https://oinkzwurgl.org" } },
        .zoomMin         = 0,
        .zoomMax         = 25,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://test",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 0,
    },
    {
        .enabled         = false,
        .name            = "test_0_20",
        .title           = "test map 0..20",
        .mapLinks        = { { "test map", "https://oinkzwurgl.org" } },
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://test",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 0,
    },
    {
        .enabled         = false,
        .name            = "nope_0_20",
        .title           = "nope map 0..20",
        .mapLinks        = { { "test map", "https://oinkzwurgl.org" } },
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://nope",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 0,
    },
    {
        .enabled         = false,
        .name            = "load_0_20",
        .title           = "load map 0..20",
        .mapLinks        = { { "test map", "https://oinkzwurgl.org" } },
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://load",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 0,
    },
    {
        .enabled         = false,
        .name            = "fail_0_20",
        .title           = "fail map 0..20",
        .mapLinks        = { { "test map", "https://oinkzwurgl.org" } },
        .zoomMin         = 0,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://fail",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 0,
    },
    {
        .enabled         = false,
        .name            = "test_10_20",
        .title           = "test map 10..20",
        .mapLinks        = { { "test map", "https://oinkzwurgl.org" } },
        .zoomMin         = 10,
        .zoomMax         = 20,
        .tileSizeX       = 256,
        .tileSizeY       = 256,
        .downloadUrl     = "builtin://test",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 0,
    },
    {
        .enabled         = false,
        .name            = "test_0_25_200x100",
        .title           = "test map 0..25 200x100",
        .mapLinks        = { { "test map", "https://oinkzwurgl.org" } },
        .zoomMin         = 0,
        .zoomMax         = 25,
        .tileSizeX       = 200,
        .tileSizeY       = 100,
        .downloadUrl     = "builtin://test",
        .subDomains      = { },
        .downloadTimeout = 5000,
        .referer         = "",
        .cachePath       = "nocache",
        .minLat          = MIN_LAT_RAD,
        .maxLat          = MAX_LAT_RAD,
        .minLon          = MIN_LON_RAD,
        .maxLon          = MAX_LON_RAD,
        .threads         = 0,
    },
};

/*static*/ const MapParams MapParams::NO_MAP =
{
    .enabled         = false,
    .name            = "nomap",
    .title           = "no map",
    .mapLinks        = { },
    .zoomMin         = 0,
    .zoomMax         = 20,
    .tileSizeX       = 256,
    .tileSizeY       = 256,
    .downloadUrl     = "builtin://nope",
    .subDomains      = { },
    .downloadTimeout = 5000,
    .referer         = "",
    .cachePath       = "nocache",
    .minLat          = MIN_LAT_RAD,
    .maxLat          = MAX_LAT_RAD,
    .minLon          = MIN_LON_RAD,
    .maxLon          = MAX_LON_RAD,
    .threads         = 0,
};

/* ****************************************************************************************************************** */
