name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checks-out
          uses: actions/checkout@v4
        - name: install packages
          run: |
            sudo apt-get -y update
            sudo apt-get -y install gcc libpath-tiny-perl libdata-float-perl
        - name: build
          run: make build
        - name: test
          run: make test
